@startuml

actor Browser
participant HttpServer
participant controllers
participant CreateSurveyController
participant SurveyDao
database postgres

Browser -> HttpServer: POST / api/createSurvey
HttpServer -> controllers: get("/api/createSurvey")
HttpServer <-- controllers: CreateSurveyController
HttpServer -> CreateSurveyController: response = handle(request)
CreateSurveyController -> CreateSurveyController: survey = new Survey()
CreateSurveyController -> CreateSurveyController: survey.setSurveyName(req.get("surveyName))\n...
note left of CreateSurveyController: Reads form parameters from request body
CreateSurveyController -> SurveyDao: save(survey)
SurveyDao -> postgres: INSERT INTO surveys ...
HttpServer <-- CreateSurveyController: OK 200
HttpServer -> HttpServer: response.write(socket)
Browser <-- HttpServer: HTTP/1.1 200 OK

@enduml